#include <GL/glew.h>
#include <GL/glfw.h>
#include <vector>
#include <string>
#include <fstream>
#include <ctime>
#include <assert.h>
#include <cstdio>

#define GLM_SWIZZLE_XYZW
#include "glm/glm.hpp"
#include "glm/gtc/type_ptr.hpp"
#include "glm/gtc/swizzle.hpp"
#include "glm/gtc/quaternion.hpp"
#include "glm/gtx/rotate_vector.hpp"
#include "glm/gtx/vector_angle.hpp"
#include "glm/gtx/compatibility.hpp"
#include "glm/gtx/matrix_operation.hpp"
#include "glm/gtx/transform.hpp"
#include "glm/gtx/quaternion.hpp"
#include "glm/gtx/euler_angles.hpp"